// r20: read the live design tokens of A · B · C (light + dark) from the running pages → assets/tokens.js
// (data for styleguide.html — the design-system page Dev uses for visual QA). Needs the dev server (npm run serve).
// usage: node tools/tokens.mjs [base=http://localhost:8765]
import { chromium } from 'playwright';
import { writeFileSync } from 'node:fs';
const BASE = process.argv[2] || process.env.BASE || 'http://localhost:8765';
const ALIAS = ['--s-card', '--s-card-2', '--s-ink', '--s-ink-2', '--s-ink-3', '--s-line', '--s-accent', '--s-on-accent', '--s-accent-soft', '--s-ok', '--s-warn', '--s-bad'];
const NAME = { a: 'A · Bento', b: 'B · Engineering Sheet', c: 'C · Virtual Showroom' };
const b = await chromium.launch({ args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const out = { generated: new Date().toISOString().slice(0, 10), alias: ALIAS, editions: {} };
for (const v of 'abc') {
  out.editions[v] = { name: NAME[v] };
  for (const scheme of ['light', 'dark']) {
    const row = {};
    for (const w of [1366, 390]) {
      const p = await b.newPage({ viewport: { width: w, height: w < 600 ? 844 : 900 }, colorScheme: scheme });
      await p.goto(`${BASE}/${v}.html`, { waitUntil: 'domcontentloaded' });
      await p.waitForFunction(() => document.documentElement.classList.contains('sx-on'), null, { timeout: 120000 });
      const r = await p.evaluate(ALIAS => {
        const cs = getComputedStyle(document.documentElement), probe = document.createElement('i');
        document.body.append(probe);
        // normalise any colour syntax (color-mix → oklab/color(srgb …)) to rgb()/rgba() by painting one pixel
        const cv = document.createElement('canvas'); cv.width = cv.height = 1; const g = cv.getContext('2d', { willReadFrequently: true });
        const rgb = c => { g.clearRect(0, 0, 1, 1); g.fillStyle = '#000'; g.fillStyle = c; g.fillRect(0, 0, 1, 1); const [r, gg, b, a] = g.getImageData(0, 0, 1, 1).data; return a === 255 ? `rgb(${r}, ${gg}, ${b})` : `rgba(${r}, ${gg}, ${b}, ${+(a / 255).toFixed(2)})`; };
        const col = name => { probe.style.color = ''; probe.style.color = `var(${name})`; return rgb(getComputedStyle(probe).color); };
        const tokens = Object.fromEntries(ALIAS.map(k => [k, col(k)]));
        const radius = cs.getPropertyValue('--s-r').trim();
        probe.remove();
        const vis = sel => [...document.querySelectorAll(sel)].find(e => e.offsetParent && e.getBoundingClientRect().height > 0);
        const type = (sel) => { const e = vis(sel); if (!e) return null; const s = getComputedStyle(e); return { sel, family: s.fontFamily.split(',')[0].replace(/["']/g, '').trim(), size: parseFloat(s.fontSize), weight: +s.fontWeight, lh: s.lineHeight === 'normal' ? null : +(parseFloat(s.lineHeight) / parseFloat(s.fontSize)).toFixed(2), track: s.letterSpacing }; };
        const bs = getComputedStyle(document.body);
        const body = { sel: 'body', family: bs.fontFamily.split(',')[0].replace(/["']/g, '').trim(), size: parseFloat(bs.fontSize), weight: +bs.fontWeight, lh: +(parseFloat(bs.lineHeight) / parseFloat(bs.fontSize)).toFixed(2), track: bs.letterSpacing };
        return { tokens, radius, bg: rgb(bs.backgroundColor), h1: type('h1'), h2: type('.sec-h h2, .sheet-h h2'), lead: type('.sec-h h2 + p, .sheet-h h2 + p'), h3: type('main h3'), body, eyebrow: type('.sec-h .eyebrow, .sheet-h .eyebrow, .eyebrow'), mono: getComputedStyle(document.documentElement).getPropertyValue('--mono').split(',')[0].replace(/["']/g, '').trim() };
      }, ALIAS);
      if (w === 1366) Object.assign(row, { tokens: r.tokens, radius: r.radius, bg: r.bg, mono: r.mono, type: { desktop: { h1: r.h1, h2: r.h2, lead: r.lead, h3: r.h3, body: r.body, eyebrow: r.eyebrow } } });
      else row.type.phone = { h1: r.h1, h2: r.h2, lead: r.lead, h3: r.h3, body: r.body, eyebrow: r.eyebrow };
      await p.close();
    }
    out.editions[v][scheme] = row;
    console.log(v, scheme, 'ok');
  }
}
await b.close();
writeFileSync(new URL('../assets/tokens.js', import.meta.url), '// generated by tools/tokens.mjs — do not edit (re-run after changing any token in a/b/c.html)\nexport default ' + JSON.stringify(out, null, 1) + ';\n');
console.log('wrote assets/tokens.js');
